#!/bin/sh

export LANG=en_US.UTF-8

clock=$(date '+%I')

case "$clock" in
	"00") icon="󱑊 " ;;
	"01") icon="󱐿 " ;;
	"02") icon="󱑀 " ;;
	"03") icon="󱑁 " ;;
	"04") icon="󱑂 " ;;
	"05") icon="󱑃 " ;;
	"06") icon="󱑄 " ;;
	"07") icon="󱑅 " ;;
	"08") icon="󱑆 " ;;
	"09") icon="󱑇 " ;;
	"10") icon="󱑈 " ;;
	"11") icon="󱑉 " ;;
	"12") icon="󱑊 " ;;
esac

date +"%A, %b %d $icon%I:%M %p"

# Clicks
case $BUTTON in

	1) # Left click: Show calendar
		setsid "$TERMINAL" -e sh -c "ncal -Mbwy; echo; read -n 1 -s -r -p 'Press any key to close...'" & ;;
		
	2) # Middle click: Show terminal clock
		setsid "$TERMINAL" -e watch -n 1 date & ;;
		# or: setsid "$TERMINAL" -e tty-clock -c -C 6 &

	3) # Right click: Edit script
		setsid "$TERMINAL" -e "$EDITOR" "$HOME/.local/bin/clock" & ;;

esac
