#!/bin/sh
# GPU temp

export LANG=en_US.UTF-8

# Sensor info
gputemp=$(sensors | awk '/^junction/ { gsub (/\+/,""); gsub(/\..*/,"",$2); print $2}')

# Sending to bar
echo $gputemp"°C"

case $BUTTON in
    
    1) # Left click: Open lact
        setsid lact & ;;

    2) # Middle click: Open btop
        setsid "$TERMINAL" -e btop & ;;

    3) # Right click: Edit this script
        setsid "$TERMINAL" -e "$EDITOR" "$HOME/.local/bin/gpu-temp" & ;;

esac
